<?xml version="1.0" encoding="utf-8"?><Database Name="TaskDB" Class="TaskModelDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDb)\v11.0;AttachDbFilename=|DataDirectory|\TaskDB.mdf;Initial Catalog=TaskDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TaskDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblTask" Member="Task">
    <Type Name="Task">
      <Column Name="TaskId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="[Level]" Member="Level" Type="System.String" DbType="Char(15) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="IsComplete" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
</Database>